### ISSUE TITLE
There is no setting to reverse an Accidental Trash and Ban

### ISSUE THREAD

**Issue by mrjarbenne** [foliovision/thoughtful-comments#28]
One other small issue I thought I would share here. Once a commenter has been banned from a site via the **Trash and Ban** functionality, there doesn't seem to be a mechanism in place to revert that ban if it was pressed accidentally (or if the banned user feels remorseful and asks nicely to be part of the community again.)

In the Comment area of the Dashboard, the text "Already Banned!" underneath the offending comment doesn't undo the ban.

Thanks again for the great plugin.

**Comment by foliovision** [comment]
Hi Jared,

WordPress has mechanisms in place to remove bans. One removes the ban via Settings:Discussion. There is a list of IP's and emails here. A separate logging and unbanning process would be a lot of redundant code with little practical application (I understand that it does have use inside an educational environment).

Making the web work for you, Alec

**Comment by mrjarbenne** [comment]
This has been solved. Thanks for the addition of the blacklist table via the Tools menu.
