### ISSUE TITLE
Code is bleeding through on front end of unapproved comments (for admins)

### ISSUE THREAD

**Issue by placoderm** [foliovision/thoughtful-comments#37]
Just installed your plugin (Version: 0.3.3) and when I have an unapproved comment (from a new user) and I go to the front end logged in as admin I can see code showing on the front end. This is what I am seeing:
![20-11-08 10_04_](https://user-images.githubusercontent.com/31570884/98457110-7241bd80-21aa-11eb-86af-32433fcc59f8.png)

And none of the links for approve, etc, are working

Here is the source code:
(sorry about the messy formatting; I'm not sure how to insert it properly)

`<div id="comment-50" class="comment odd alt thread-odd thread-alt depth-1">
				<article id="div-comment-50" class="comment-body">
					<footer class="comment-meta">
						<div class="comment-author vcard">
							<img alt="" src="https://secure.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=120&amp;d=retro&amp;r=g" class="avatar avatar-120 photo" loading="lazy" width="120" height="120"><span class="fn">&lt;span id="comment-50-unapproved" class="tc_highlight"&gt;John&lt;/span&gt;</span><span class="screen-reader-text says">says:</span>						</div>
						<div class="comment-metadata">
							<a href="https://school.serenecolombo.org/g1-l1-deer-hunter/#comment-50">
																<time datetime="2020-11-08T10:03:27+05:30" title="November 8, 2020 at 10:03 am">
									November 8, 2020 at 10:03 am								</time>
							</a>
							 <span aria-hidden="true">•</span> <a class="comment-edit-link" href="https://school.serenecolombo.org/wp-admin/comment.php?action=editcomment&amp;c=50">Edit</a>						</div>
					</footer>
					<div class="comment-content entry-content">
						 This is another comment
Approve Trash Trash Thread Trash &amp; Ban | Trash Thread &amp; Ban
							<p class="comment-awaiting-moderation">Your comment is awaiting moderation.</p>
					</div>`

**Comment by foliovision** [comment]
Hello snow1776,

we insert the code in a way which doesn't require any template modifications, but I see that in some cases it might fail.

Please let us know what template you are using and if it works for you when you try TwentyTwenty.

Thanks,
Martin

**Comment by placoderm** [comment]
Hello! Thanks for the quick reply.

I am indeed using twentytwenty. Actually a child theme, but I switched back to the parent theme.

Please let me know if there is anything else you need. I can duplicate the site and give you access if you need.

**Comment by foliovision** [comment]
Hello snow1776,

please reinstall from https://github.com/foliovision/thoughtful-comments/archive/master.zip and it should be all working fine. Then we can make it a new release.

Thanks,
Martin

**Comment by placoderm** [comment]
> please reinstall from...

Ah! It works. Thank you so much. 

Will I need to uninstall this version once you publish the real thing on WP.org?

I really appreciate your help. This plugin is exactly what we need and will make our project run more smoothly. I wish your plugin was more famous.

**Comment by foliovision** [comment]
Hello snow1776,

I did put this new release on WP.org. You should see the update soon and it should just work.

Thanks,
Martin

**Comment by placoderm** [comment]
Thank You!
